apiVersion: v1
kind: ConfigMap
metadata:
  name: kamailio-config
  namespace: kamailio
data:
  kamailio.cfg: |
    #!KAMAILIO
    # Kamailio SIP Server Configuration
    # Enhanced configuration for SIP testing
    
    ####### Global Parameters #########
    debug=2
    log_stderror=yes
    log_facility=LOG_LOCAL0
    
    /* number of children processes to be created for handling requests */
    children=4
    
    /* add local domain aliases */
    alias="kamailio.local"
    
    /* listen addresses */
    listen=udp:0.0.0.0:5060
    listen=tcp:0.0.0.0:5060
    
    /* core modules */
    loadmodule "tm.so"
    loadmodule "sl.so"
    loadmodule "xlog.so"
    
    /* routing logic */
    request_route {
        # Log all requests
        xlog("L_INFO", "Received SIP request\n");
        
        # Send 200 OK for all requests
        sl_send_reply("200", "OK");
        exit;
    } 