apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kamailio

resources:
- namespace.yaml
- configmap.yaml
- mysql-deployment.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

# Lägg till labels endast på specifika resurser (inte MySQL)
patches:
- target:
    kind: Deployment
    name: kamailio
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app: kamailio
        project: sip-k8s-lab
- target:
    kind: Service
    name: kamailio-service
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app: kamailio
        project: sip-k8s-lab
- target:
    kind: Service
    name: kamailio-internal
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app: kamailio
        project: sip-k8s-lab
- target:
    kind: Ingress
    name: kamailio-ingress
  patch: |-
    - op: add
      path: /metadata/labels
      value:
        app: kamailio
        project: sip-k8s-lab 