apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kamailio

resources:
- namespace.yaml
- configmap.yaml
- mysql-deployment.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: kamailio
  project: sip-k8s-lab 