apiVersion: v1
kind: Service
metadata:
  name: kamailio-service
  namespace: kamailio
  labels:
    app: kamailio
    component: sip-proxy
spec:
  type: LoadBalancer
  ports:
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    targetPort: 5060
    protocol: TCP
  - name: sip-tls
    port: 5061
    targetPort: 5061
    protocol: TCP
  selector:
    app: kamailio
---
apiVersion: v1
kind: Service
metadata:
  name: kamailio-internal
  namespace: kamailio
  labels:
    app: kamailio
    component: sip-proxy
spec:
  type: ClusterIP
  ports:
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    targetPort: 5060
    protocol: TCP
  - name: sip-tls
    port: 5061
    targetPort: 5061
    protocol: TCP
  selector:
    app: kamailio 